apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
  labels:
    app: myflask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
      - name: flaskapp
        image: minalmahor/myflask
        ports:
        - containerPort: 5001
