apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-minal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minal.com
    http:
      paths: 
       - backend:
          serviceName: myflask
          servicePort: 5001
